```plantuml
@startuml
'condicional
skinparam ActivityDiamondBackgroundColor #CAD500
skinparam ActivityDiamondBorderColor #004D71
'resto
skinparam shadowing false
skinparam ActivityArrowColor #004D71
skinparam ActivityBackgroundColor #CAD500
skinparam ActivityBorderColor #004D71

title Diagrama de flujos para el chatbot de Enagas\n
start
:enagasChatbotApp.js]
  split
    :dev.private.js]
    detach
  split again
    while (front-end/iecisaFrontEnd.js)
    split
      :front-end/indexV2.pug]
    split again
      while (providers/iasApiClientes.js)
      :providers/microsoft-resources/luisGetIntent.js]
      if (¿Usar integración con Remedy?) then (sí)
      :assets/soapClientRemedy.js]
      else (no)
      endif
      :respuesta API Rest;
      stop
      endwhile
    split again
      :assets/getApiContents.js]
    end split
    endwhile
  end split
  :respuesta en el front-end;
  stop
@enduml
```